file/urls.py
from django.conf.urls import url
from . import views

app_name = 'file'

urlpatterns = [
    # /file/
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    # /file/<folder_id>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /file/folders/
    url(r'^folders/$', views.MyFoldersView.as_view(), name='folders'),

    # /file/folders/add/
    url(r'folders/add/$', views.FolderCreate.as_view(), name='folder-add'),

    # /file/folders/<folder_id>
    url(r'folders/(?P<pk>[0-9]+)/$', views.FolderUpdate.as_view(), name='folder-update'),

    # file/folders/<folder_id>/delete
    url(r'folders/(?P<pk>[0-9]+)/delete/$', views.FolderDelete.as_view(), name='folder-delete'),

    # file/receipt/add/
    url(r'^receipt/add/$', views.ReceiptCreate.as_view(), name='receipt-add'),

    # file/<receipt_id>/delete
    url(r'^(?P<pk>[0-9]+)/delete/$', views.ReceiptDelete.as_view(), name='receipt-delete'),

    # file/<receipt_id>/update
    url(r'^(?P<pk>[0-9]+)/update/$', views.ReceiptUpdate.as_view(), name='receipt-update'),
]

moneyproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^file/', include('file.urls')),
    url(r'^admin/', admin.site.urls),
]

file/models.py
from django.db import models
from django.db.models import Sum
from django.core.urlresolvers import reverse


class Folder(models.Model):
    name = models.CharField(max_length=250)

    def get_absolute_url(self):
        return reverse('file:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

    def get_total(self):
        total = 0
        for receipt in self.receipt_set.all():
            total += receipt.amount

        return total


class Receipt(models.Model):
    folder = models.ForeignKey(Folder, on_delete=models.CASCADE)
    store = models.CharField(max_length=250)
    date = models.CharField(max_length=15)
    # i.e car upkeep, groceries, rent, water bill...ect, ect
    amount = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)

    def get_absolute_url(self):
        return reverse('file:detail', kwargs={'pk': self.folder.pk})

    def __str__(self):
        return self.store + ' date: ' + self.date

file/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

file/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Folder, Receipt
from django.db.models import Sum
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm

total = Folder.objects.all().aggregate(receipt_total=Sum('receipt__amount'))

class IndexView(generic.TemplateView):
    template_name = 'file/index.html'


class DetailView(generic.DetailView):
    model = Folder
    template_name = 'file/details.html'

    def get_total(self):
        total = Folder.objects.filter(self).aggregate(Sum('receipt__amount'))
        return total

# >>>>>>> FOLDER VIEWS >>>>>>>>


class MyFoldersView(generic.ListView):
    template_name = 'file/folders.html'
    context_object_name = 'all_folders'

    def get_queryset(self):
        return Folder.objects.all()


class FolderCreate(CreateView):
    model = Folder
    fields = ['name']


class FolderUpdate(UpdateView):
    model = Folder
    fields = ['name']


class FolderDelete(DeleteView):
    model = Folder
    success_url = reverse_lazy('file:folders')

# >>>>>>> RECEIPT VIEWS >>>>>>>>>>>>


class ReceiptCreate(CreateView):
    model = Receipt
    fields = ['folder', 'store', 'date', 'amount']


class ReceiptUpdate(UpdateView):
    model = Receipt
    fields = ['store', 'date', 'classification']


class ReceiptDelete(DeleteView):
    model = Receipt
    success_url = reverse_lazy('file:folders')


class UserFormView(View):
    form_class = UserForm
    template_name = 'file/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('file:index')

        return render(request, self.template_name, {'form': form})

file/templates/file/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Balance{% endblock %}</title>


    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'file/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Logo -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'file:index' %}">Balance</a>
        </div>

        <!-- items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">

            </ul>
            <!--
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            -->
            <ul class="nav navbar-nav navbar-right">
                  <!-- additional buttons -->
                <li class="">
                    {% block nav1 %}
                    {% endblock %}

                <!-- START dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                        <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>
                    </a>
                    <ul class="dropdown-menu">

                        <li class="">
                            <a href="{% url 'file:folders' %}">
                                <span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>&nbsp; My Folders
                            </a>
                        </li>

                        <li>
                            <a href="{% url 'file:folder-add' %}">
                                <span class="glyphicon glyphicon-folder-close" aria-hidden="true"></span>&nbsp; Add Folder
                            </a>
                        </li>

                        <li>
                            <a href="{% url 'file:receipt-add' %}">
                                <span class="glyphicon glyphicon-file" aria-hidden="true"></span>&nbsp; Add Receipt
                            </a>
                        </li>

                    </ul>
                </li>
                <!-- END DROPDOWN -->

                 <!-- log out -->
                 <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>

        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

file/templates/file/details.html
{% extends 'file/base.html' %}
{% block title %}Folder Details{% endblock %}

{% block body %}

    <div class="container-fluid">
        <div class="panel panel-info">

            <div class="panel-heading">{{ folder.name }}

            </div>

            <table class="table">
                <tr>
                    <th>Name</th>
                    <th>Date</th>
                    <th>Amount</th>
                    <th>Option</th>
                </tr>

                {% for receipt in folder.receipt_set.all %}

                <tr>
                    <td>{{ receipt.store }}</td>
                    <td>{{ receipt.date }}</td>
                    <td>$ {{ receipt.amount }}</td>
                    <td>Drop down here</td>
                </tr>

                {% endfor %}

                <tr>
                    <td><b>TOTAL</b></td>
                    <td></td>
                    <td><b>$ {{ folder.get_total }}</b></td>
                    <td></td>
                </tr>

            </table>
        </div>

    </div>

{% endblock %}

file/templates/file/folder_form.html
{% extends 'file/base.html' %}
{% block title %}Add a New Folder{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'file/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>


{% endblock %}

file/templates/file/folders.html
{% extends 'file/base.html' %}

{% block body %}
    <div class="container-fluid">




            <div class="panel panel-info">
                <!-- Panel heading -->
                <div class="panel-heading">My Folders</div>

                <!-- Table -->
                <table class="table">
                    <tr>
                        <th>Name</th>
                        <th></th>
                        <th></th>
                    </tr>
                    {% for folder in all_folders %}
                    <tr>
                        <!-- Open Folder -->
                        <td>
                            <a href="{% url 'file:detail' folder.id %}">
                                <button type="button" class="btn btn-default btn-primary">{{ folder.name }}
                                    <span class="glyphicon glyphicon-folder-open"></span>
                                </button>
                            </a>
                        </td>

                        <!-- Edit Folder -->
                        <td>
                            <a href="{% url 'file:folder-update' folder.id %}">
                                <button type="button" class="btn btn-defualt btn-info">Edit Folder
                                    <span class="glyphicon glyphicon-edit"></span>
                                </button>
                            </a>
                        </td>
                        <!-- Delete Folder -->
                        <td>
                             <form action="{% url 'file:folder-delete' folder.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="folder_id" value="{{ folder.id }}"/>
                                <button type="submit" class="btn btn-default btn-danger"> Delete Folder
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                             </form>
                        </td>
                    </tr>
                    {% endfor %}
                </table>

            </div>

        </div>

{% endblock %}

file/templates/file/form-template.html
{% for field in form %}

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <lable class="control-lable col-sm-2">{{ field.label_tag}}</lable>
        <div class="col-sm-10">{{ field }}</div>
    </div>

{% endfor %}

file/templates/file/index.html
{% extends 'file/base.html' %}

{% block body %}
    <h1>Hello, this is home page</h1>
{% endblock %}

file/templates/file/receipt_form.html
{% extends 'file/base.html' %}
{% block title %}Add a New Receipt{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'file/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>


{% endblock %}

file/templates/file/registration_form.html
{% extends 'file/base.html' %}
{% block title %}Register{% endblock %}


{% block body %}

<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create a new Account</h3>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'file/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>

                        </div>

                    </form>

                </div>

            </div>

        </div>

    </div>

</div>


{% endblock %}